language: python
python:
- '3.6'
- '2.7'
before_install:
- "./ecr_credentials.sh"
install:
- pip install -r requirements.txt
before_script:
- cd demo
script:
- python manage.py test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
env:
  global:
  - secure: iIHopsSCezckReLOTbTVwNRRYEBz8y7KdJe7V3V5OGcPRvQS/8nGfvFbRjeodO+DcWiGQE2m8CN1E+n1gzX3EPT5FKmnKo4Uhw+hqXq2H6YjU/VTCpaM+xYyrPLPqAJAOVeZadUi+9Boa8RmXdyEG5S1gz+gnWXYcQ5sXv6jK2EM/lH/XW92VGxs8C8zBatC0vC4b/S/DJ8q1Kd3d71N1Gqfgk/5o2wG1QGPxMjJqZEqvlbAjecwwoE3+vMrw7ATFqFGonRXojkm9kLoMqpogoENNlfnhb0N8/vEjXY2V754HXdlZhmaEk+NmxrPAdkfbmgrIPKS7qRqRx5DIBCjVUMb+n4CGhiSEjrAgNBCQRP4NOyJ/S7qxBS9Xq/O0AmfEtzMh6LGUDm/fK7A2ASOWxMZ4xfat8xMJ5UyFroByar8qYwwE8TwkjpF5XZeBgdPJkdYQ5f8VqIYMJdZAvZZg9vkwCo1UmFgcUl/YieMnp9F+OOL2uV0TfFhxNsCszfKHqieKeYxwjt8F6E7dfwOUhBaTYDN7cC6NYmehOw/2YMk2DJRW3KCeWGe6Du4ajizgCGtUmnYwDgcH2b552Mo584uGNmqwdq55Q/9jMUcIzRNBRHdjgdaLbAJEVbYP5mClthndeysxtOxvZhTmr4QZdEZ9JRjr7uKbfksZBvynQo=
  - secure: Aw1LOkxG5Rur3y5rpiXyccYskPanrc2N9i1RVG/XDuAsuvNqZgnWiibAVw+UJ4XSuAR6S+22yKK9niwagWC5STiOIpGxvyxhFdg7GvpsqnJsJKmAgD5FK5lMjl0MRbbXm7njEXfY6HOXRvPo+MJLPooiaXTLvLgUOXlkpjL/bJUIklsNVsPmJOmtLr3UYs0Hr7xeo8TXC4u+22s1K7XFFCb7cm5NdlhXfezHmeLLH5Ug+eHUKdJhQy+YV1hQUJHQtqmQcFXB4lCWDHWMit4OHDdfMCdRCSXdzyd5Mv//xpRD25SLo5XtXG0/Pjap13n4xyyeZfcxvORSxJoT99YCqyBwxw3wDCu0vklv60hWlVemxBVrKxT04QrQFI5StlkCrp4VlnAacTCZKmc6bNPQYWpqaN6SgZ2bI50TfvGmBAyPuFoycCLh/0j+zqbom1ZQuK6E8nocdY4N2BdEKhw6dspmxpBgsPgAF/RvMA5afq2BrAlQAG1I3jelprnvWoBAM1B39mCdmLh4YiAsI1vjiJhjpcgFssqUOjsjB0sGYTiXaUbluBKwIxjoCYAvMoiysqPeL/Hu8QGp1aQJ8BDnhHcbUEosoqYPa50fOD96LiUcyRQobTbMi3kiwCSo2OTwQRy6CqO0sgawcvxLqD8vl16iWtXPVl4E2W1Ojoo6AHk=
