language: python
python:
  - "3.6"
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
before_script:
  - cd demo
script:
  - python manage.py test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
