dist: xenial

matrix:
  include:
    - language: python
      python:
        - '3.6'
      install:
        - pip install -r requirements.txt
      before_script:
        - cd app/server
      script:
        - python manage.py test crawler rekognition

    - language: node_js
      node_js: '11.10.0'
      before_install:
        - cd app/client
        - npm i -g npm@6.7.0
      install:
        - npm install
      script:
        - npm run coverage

notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
