language: python
python:
  - '3.6'
before_install:
  - chmod +x ./aws_credentials.sh
  - ./aws_credentials.sh
install:
  - pip install -r requirements.txt
before_script:
  - cd demo
script:
  - python manage.py test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
env:
  global:
  - secure: iG3oGJLGhN9gG83YEyoVOcpxNyGvLsM73EstCVFkWqOqbPMphk3czMwUOBSgrSCjmTScT5VmywIooaoA0jVjTm6MJ+AvwEdoS7ea/cM75x7dSY4BpdAMOqXzgTWGN22NFC/bwQnmUXtUyvFbG1KIq/lYsNVCMXIz2grf11SBVM9+/xOd//yG/AZXGcNKAoRpvqSiqT/Ogt2x/dtW/70hj3qUtn9CABbgqM01ntVtRvGC2kdBMP7LZfikY03WPsYRLjT1EIQc+nfv9UkpcvDx16sorI1hIxN340mqLJ2bRcWkDpJhnZYFkVJPgb8Lr/vbQIg8m/73iVnNrP2/z2xGftDUEidM8dcQNcWtLmXzW6oICHLdv+GBMUoqoIjPfjBu6yiW4QcD6yqKbCG5HBzO55gBH/OxDBC6yQan6BkQwdTsm/M1N0QPcCYYswcHIU7myeQyetr5Ppc2NvJYq0UHtrxI2WwLpeLOQUWxzjtmWjcuxKiAk5U/uh6DJMikWj/0quqIkzPWFB2F8dpc6+u2CyIYBT7fRMP5tR0Yo8ODnfd5cyWPLu2sdAvSN/JeoAYM2xZFfqm6I72tycFmv08tfU/9NGQGbTBjnOLawV+hH6hQHeCfU65FWqqwX4kQgFQUuLOYQ+EvKlQ7dQE/jxCiOzlcItDy0Hr8e2SeCqmDFQE=
  - secure: TvcO1rNZzAguQFMrbgas60yO0redVwcLNwqXIGk23U5bJDuMJEb6+oyaK8LrT09pZnDAgH3DYPPLM0xioywAHS0xK8zmIuZV4vAnfPSMLJpn7LwKGweL+dMfkpN5lPce4qKsY6cppC8KNmIPynGAEKPzoeZSdFoyRGy6h4nYF2NsxkQXmQsnOHtXidU8c+9upUapTWBYIj7N04WryWpi3I7gdbK80smgevAut7Of4h+x7ewaA2dJ5QtcuMlz0WBAj3WqlVSOEgsmNzXmnhh+jFOga3MKZkr0AnfW8jBvehK68zeu9K6twoVOiOhYnQDmuYx2pQtoH4Fj77jOPMZvdTanI4Gj59RhqNApQGEajG77+BdkNdetdEUynOiW0s7JO0iD9KCH8TfJ5WiaFrZ6hKAUb8ziChgWAm88iXk7JrlvV17c4Uc7t285/EyLum2OZCN5OHrzQjyXVT2k61LgjoZjbWm4v9nmSPyerAgdYYQUnc6CWCxF6TmPrZkP9SVcqYA+InkyAG88kCutwEeGdrwZ3qDpXQ0UfPQJjRC2LmZREFtTZWusm4BbZWqyLHVs30GcCQHaom695D/4jI4bn21AiQN6KDTVQbBwoJ8EpSd0R1uscGtopbMjksKr/6IdvF1gZENkTAw9sb1+O4KpJl1DOn3PeValk7/ILmwHvTg=
